# Generated by Django 4.2.8 on 2026-03-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_sample_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='gia_ban',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='han_su_dung',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='mau_sac',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='ngay_tao',
        ),
        migrations.AddField(
            model_name='sanpham',
            name='ty_le_loi_nhuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='vai_tro',
            field=models.CharField(choices=[('Admin', 'Ch? c?a hàng'), ('NhanVien', 'Nhân viên kho'), ('GiaoHang', 'Giao hàng')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='gia_nhap',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
